CREATE TABLE station (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city VARCHAR(255) NOT NULL
);

CREATE TABLE customer (
    customer_number INTEGER PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL
);

CREATE TABLE house (
    house_nr VARCHAR(255) PRIMARY KEY,
    price INTEGER NOT NULL,
    street VARCHAR(255) NOT NULL,
    model VARCHAR(255) NOT NULL,
    image_url VARCHAR(1024),
    station_id INTEGER REFERENCES station (id)
);

CREATE TABLE rental (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rental_date DATE NOT NULL,
    return_date DATE,
    km INTEGER,
    driver_customer_number INTEGER NOT NULL REFERENCES customer (customer_number),
    house_nr VARCHAR(255) NOT NULL REFERENCES house (house_nr),
    rental_station_id INTEGER NOT NULL REFERENCES station (id),
    return_station_id INTEGER REFERENCES station (id)
);

CREATE INDEX idx_house_station ON house (station_id);
CREATE INDEX idx_rental_house ON rental (house_nr);
-- Running rentals are read on every page load and by the running-rentals gauge.
CREATE INDEX idx_rental_running ON rental (return_date, km, return_station_id);
