apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: renthub

resources:
  - ../../base

patches:
  - path: replicas.yaml
    target:
      kind: Deployment
      name: renthub

images:
  - name: ghcr.io/vladikiva/renthub
    newTag: v0.1.0
