apiVersion: apps/v1
kind: Deployment
metadata:
  name: renthub
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: app
          env:
            - name: LOG_LEVEL_ROOT
              value: WARN
          resources:
            requests:
              cpu: 500m
              memory: 768Mi
            limits:
              memory: 1Gi
